In [1]:
import numpy as np

In [2]:
item_quantity = [5, 2, 10, 5, 4]

In [3]:
item_quanity_np = np.array(item_quantity)

In [4]:
type(item_quanity_np)

numpy.ndarray

In [5]:
item_quanity_np

array([ 5,  2, 10,  5,  4])

In [6]:
item_quanity_np.shape

(5,)

In [7]:
item_quanity_np.ndim

1

In [8]:
item_quanity_np[0]

5

In [9]:
item_quanity_np[0:3]

array([ 5,  2, 10])

In [10]:
array2d = np.array([[1,2,3],[5,10,15]])
array2d

array([[ 1,  2,  3],
       [ 5, 10, 15]])

In [11]:
array2d.shape

(2, 3)

In [12]:
array2d.ndim

2

In [13]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
array2d = np.array([[1,2,3],[5,10,15],[7,8,9]])

In [16]:
array2d

array([[ 1,  2,  3],
       [ 5, 10, 15],
       [ 7,  8,  9]])

In [17]:
array2d[1,1]

10

In [18]:
array2d[1,2]

15

In [19]:
array2d[0:2,]

array([[ 1,  2,  3],
       [ 5, 10, 15]])

In [20]:
array2d[0:2,2]

array([ 3, 15])

In [21]:
array1d = np.array([1,2,3,4,5,6])
array1d

array([1, 2, 3, 4, 5, 6])

In [22]:
array1d.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
item_quanity_np

array([ 5,  2, 10,  5,  4])

In [24]:
item_quanity_np + 1

array([ 6,  3, 11,  6,  5])

In [25]:
item_quanity_np * 10

array([ 50,  20, 100,  50,  40])

In [26]:
item_quanity_np ** 2

array([ 25,   4, 100,  25,  16], dtype=int32)

In [27]:
item_quanity_np

array([ 5,  2, 10,  5,  4])

In [28]:
item_paid_np = np.array([500, 800, 1200, 80, 200])

In [29]:
item_paid_np

array([ 500,  800, 1200,   80,  200])

In [30]:
item_paid_np / item_quanity_np

array([100., 400., 120.,  16.,  50.])

In [31]:
item_paid_np

array([ 500,  800, 1200,   80,  200])

In [32]:
item_paid_np.max()

1200

In [33]:
item_paid_np.min()

80

In [34]:
item_paid_np.std()

407.6076544914239

In [35]:
np.percentile(item_paid_np, 50)

500.0

In [36]:
np.percentile(item_paid_np, 75)

800.0

In [37]:
array2d

array([[ 1,  2,  3],
       [ 5, 10, 15],
       [ 7,  8,  9]])

In [38]:
array2d.mean()

6.666666666666667

In [39]:
array2d.std()

4.189935029992179

Z score = (x - mean)/ sd

In [40]:
item_quanity_np

array([ 5,  2, 10,  5,  4])

In [41]:
mu = item_quanity_np.mean()
sd = item_quanity_np.std()

In [42]:
mu

5.2

In [43]:
sd

2.6381811916545836

In [44]:
(item_quanity_np - mu)/sd

array([-0.0758098 , -1.21295687,  1.8194353 , -0.0758098 , -0.45485883])

### Pandas

In [54]:
import pandas as pd

In [55]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [57]:
item_quantity

[5, 2, 10, 5, 4]

In [58]:
item_quantity_pd = pd.Series(item_quantity)
item_quantity_pd

0     5
1     2
2    10
3     5
4     4
dtype: int64

In [59]:
type(item_quantity_pd)

pandas.core.series.Series

In [60]:
item_quantity_pd.describe()

count     5.000000
mean      5.200000
std       2.949576
min       2.000000
25%       4.000000
50%       5.000000
75%       5.000000
max      10.000000
dtype: float64

#### Pandas dataframes

In [62]:
res = pd.DataFrame(array2d)
type(res)

pandas.core.frame.DataFrame

In [63]:
res = pd.DataFrame({"qty":item_quantity, "revenue":item_paid_np})

In [64]:
type(res)

pandas.core.frame.DataFrame

In [65]:
res

qty  revenue
0    5      500
1    2      800
2   10     1200
3    5       80
4    4      200

#### Loading the sales data

In [66]:
sales0 = pd.read_csv("sales_data.csv")

In [67]:
type(sales0)

pandas.core.frame.DataFrame

In [68]:
sales0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8399 entries, 0 to 8398
Data columns (total 12 columns):
Ord_id                  8399 non-null object
Prod_id                 8399 non-null object
Ship_id                 8399 non-null object
Cust_id                 8399 non-null object
Sales                   8399 non-null float64
Discount                8399 non-null float64
Order_Quantity          8399 non-null int64
Profit                  8399 non-null float64
Shipping_Cost           8399 non-null float64
Product_Base_Margin     8336 non-null float64
Product_Category        8399 non-null object
Product_Sub_Category    8399 non-null object
dtypes: float64(5), int64(1), object(6)
memory usage: 787.5+ KB


In [70]:
sales0.head(4)

Ord_id  Prod_id   Ship_id    Cust_id   Sales  Discount  Order_Quantity  \
0  Ord_5446  Prod_16  SHP_7609  Cust_1818  136.81      0.01              23   
1  Ord_2978  Prod_16  SHP_4112  Cust_1088  305.05      0.04              27   
2  Ord_5484  Prod_16  SHP_7663  Cust_1820  322.82      0.05              35   
3  Ord_3730  Prod_16  SHP_5175  Cust_1314  459.08      0.04              34   

   Profit  Shipping_Cost  Product_Base_Margin Product_Category  \
0  -30.51           3.60                 0.56  OFFICE SUPPLIES   
1   23.12           3.37                 0.57  OFFICE SUPPLIES   
2  -17.58           3.98                 0.56  OFFICE SUPPLIES   
3   61.57           3.14                 0.60  OFFICE SUPPLIES   

            Product_Sub_Category  
0  SCISSORS, RULERS AND TRIMMERS  
1  SCISSORS, RULERS AND TRIMMERS  
2  SCISSORS, RULERS AND TRIMMERS  
3  SCISSORS, RULERS AND TRIMMERS

In [71]:
sales0.tail()

Ord_id  Prod_id   Ship_id    Cust_id     Sales  Discount  \
8394  Ord_5467  Prod_14  SHP_7639  Cust_1803   5964.19      0.10   
8395   Ord_825  Prod_14  SHP_1132   Cust_247  27663.92      0.05   
8396  Ord_5368  Prod_14  SHP_7497  Cust_1795  17279.62      0.04   
8397  Ord_1765  Prod_14  SHP_2446   Cust_595  14647.26      0.07   
8398  Ord_3610  Prod_14  SHP_4998  Cust_1266   1759.65      0.06   

      Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin  \
8394              33   988.20          24.49                 0.46   
8395               8  -391.92          24.49                 0.37   
8396              40  4176.25          24.49                 0.52   
8397              25  5485.15          24.49                 0.37   
8398               3 -2213.75          24.49                 0.50   

     Product_Category Product_Sub_Category  
8394       TECHNOLOGY      COPIERS AND FAX  
8395       TECHNOLOGY      COPIERS AND FAX  
8396       TECHNOLOGY      COPIERS AND FAX  
8397       TECHNOLOGY      COPIERS AND FAX  
8398       TECHNOLOGY      COPIERS AND FAX

In [72]:
sales0.describe()

Sales     Discount  Order_Quantity        Profit  Shipping_Cost  \
count   8399.000000  8399.000000     8399.000000   8399.000000    8399.000000   
mean    1775.878179     0.049671       25.571735    181.184424      12.838557   
std     3585.050525     0.031823       14.481071   1196.653371      17.264052   
min        2.240000     0.000000        1.000000 -14140.700000       0.490000   
25%      143.195000     0.020000       13.000000    -83.315000       3.300000   
50%      449.420000     0.050000       26.000000     -1.500000       6.070000   
75%     1709.320000     0.080000       38.000000    162.750000      13.990000   
max    89061.050000     0.250000       50.000000  27220.690000     164.730000   

       Product_Base_Margin  
count          8336.000000  
mean              0.512513  
std               0.135589  
min               0.350000  
25%               0.380000  
50%               0.520000  
75%               0.590000  
max               0.850000

In [73]:
sales0.shape

(8399, 12)

#### Accessing values from a dataframe

In [75]:
type(sales0.Discount)

pandas.core.series.Series

In [76]:
sales0.Discount.describe()

count    8399.000000
mean        0.049671
std         0.031823
min         0.000000
25%         0.020000
50%         0.050000
75%         0.080000
max         0.250000
Name: Discount, dtype: float64

In [78]:
sales0['Discount'].describe()

count    8399.000000
mean        0.049671
std         0.031823
min         0.000000
25%         0.020000
50%         0.050000
75%         0.080000
max         0.250000
Name: Discount, dtype: float64

In [79]:
sales0[["Discount","Sales"]]

Discount     Sales
0         0.01    136.81
1         0.04    305.05
2         0.05    322.82
3         0.04    459.08
4         0.06    207.21
...        ...       ...
8394      0.10   5964.19
8395      0.05  27663.92
8396      0.04  17279.62
8397      0.07  14647.26
8398      0.06   1759.65

[8399 rows x 2 columns]

#### loc and iloc methods

In [81]:
sales0.iloc[0:5,0:3]

Ord_id  Prod_id   Ship_id
0  Ord_5446  Prod_16  SHP_7609
1  Ord_2978  Prod_16  SHP_4112
2  Ord_5484  Prod_16  SHP_7663
3  Ord_3730  Prod_16  SHP_5175
4  Ord_4143  Prod_16  SHP_5771

In [82]:
sales0.iloc[0:100, 4:6]

Sales  Discount
0   136.81      0.01
1   305.05      0.04
2   322.82      0.05
3   459.08      0.04
4   207.21      0.06
..     ...       ...
95  459.26      0.08
96  600.22      0.08
97   92.63      0.05
98  351.27      0.08
99  450.66      0.01

[100 rows x 2 columns]

In [85]:
?sales0.loc

In [84]:
sales0.loc[0:5, ["Discount","Sales"]]

Discount   Sales
0      0.01  136.81
1      0.04  305.05
2      0.05  322.82
3      0.04  459.08
4      0.06  207.21
5      0.09   95.09

#### Filtering data from a dataframe

In [86]:
sales0.head()

Ord_id  Prod_id   Ship_id    Cust_id   Sales  Discount  Order_Quantity  \
0  Ord_5446  Prod_16  SHP_7609  Cust_1818  136.81      0.01              23   
1  Ord_2978  Prod_16  SHP_4112  Cust_1088  305.05      0.04              27   
2  Ord_5484  Prod_16  SHP_7663  Cust_1820  322.82      0.05              35   
3  Ord_3730  Prod_16  SHP_5175  Cust_1314  459.08      0.04              34   
4  Ord_4143  Prod_16  SHP_5771  Cust_1417  207.21      0.06              24   

   Profit  Shipping_Cost  Product_Base_Margin Product_Category  \
0  -30.51           3.60                 0.56  OFFICE SUPPLIES   
1   23.12           3.37                 0.57  OFFICE SUPPLIES   
2  -17.58           3.98                 0.56  OFFICE SUPPLIES   
3   61.57           3.14                 0.60  OFFICE SUPPLIES   
4  -78.64           6.14                 0.59  OFFICE SUPPLIES   

            Product_Sub_Category  
0  SCISSORS, RULERS AND TRIMMERS  
1  SCISSORS, RULERS AND TRIMMERS  
2  SCISSORS, RULERS AND TRIMMERS  
3  SCISSORS, RULERS AND TRIMMERS  
4  SCISSORS, RULERS AND TRIMMERS

In [87]:
sales0.Order_Quantity.describe()

count    8399.000000
mean       25.571735
std        14.481071
min         1.000000
25%        13.000000
50%        26.000000
75%        38.000000
max        50.000000
Name: Order_Quantity, dtype: float64

In [88]:
sales0.Order_Quantity >= 40

0       False
1       False
2       False
3       False
4       False
        ...  
8394    False
8395    False
8396     True
8397    False
8398    False
Name: Order_Quantity, Length: 8399, dtype: bool

In [90]:
sales0.loc[sales0.Order_Quantity >= 40,]

Ord_id  Prod_id   Ship_id    Cust_id     Sales  Discount  \
11    Ord_1429  Prod_16  SHP_1976   Cust_510    539.06      0.05   
12    Ord_2471  Prod_16  SHP_3386   Cust_965     90.93      0.05   
15     Ord_956  Prod_16  SHP_1324   Cust_346    503.17      0.01   
16     Ord_975  Prod_16  SHP_1345   Cust_346    638.91      0.02   
19    Ord_4328  Prod_16  SHP_6033  Cust_1440    103.03      0.07   
...        ...      ...       ...        ...       ...       ...   
8382  Ord_5425  Prod_14  SHP_7580  Cust_1799  27720.98      0.07   
8384  Ord_1265  Prod_14  SHP_1749   Cust_466  24051.49      0.07   
8388   Ord_508  Prod_14   SHP_686   Cust_186  19109.61      0.10   
8390   Ord_546  Prod_14   SHP_858   Cust_198  27875.54      0.00   
8396  Ord_5368  Prod_14  SHP_7497  Cust_1795  17279.62      0.04   

      Order_Quantity    Profit  Shipping_Cost  Product_Base_Margin  \
11                42   -123.07           4.59                 0.82   
12                43    -72.50           2.56                 0.55   
15                46    -10.21           4.68                 0.59   
16                49     77.48           3.14                 0.60   
19                49    -82.63           2.56                 0.55   
...              ...       ...            ...                  ...   
8382              46  11984.40          24.49                 0.37   
8384              41   9791.04          24.49                 0.37   
8388              40   -379.29          24.49                 0.36   
8390              46   -635.69          24.49                 0.44   
8396              40   4176.25          24.49                 0.52   

     Product_Category           Product_Sub_Category  
11    OFFICE SUPPLIES  SCISSORS, RULERS AND TRIMMERS  
12    OFFICE SUPPLIES  SCISSORS, RULERS AND TRIMMERS  
15    OFFICE SUPPLIES  SCISSORS, RULERS AND TRIMMERS  
16    OFFICE SUPPLIES  SCISSORS, RULERS AND TRIMMERS  
19    OFFICE SUPPLIES  SCISSORS, RULERS AND TRIMMERS  
...               ...                            ...  
8382       TECHNOLOGY                COPIERS AND FAX  
8384       TECHNOLOGY                COPIERS AND FAX  
8388       TECHNOLOGY                COPIERS AND FAX  
8390       TECHNOLOGY                COPIERS AND FAX  
8396       TECHNOLOGY                COPIERS AND FAX  

[1875 rows x 12 columns]

In [94]:
sales0[sales0.Order_Quantity>=40]

Ord_id  Prod_id   Ship_id    Cust_id     Sales  Discount  \
11    Ord_1429  Prod_16  SHP_1976   Cust_510    539.06      0.05   
12    Ord_2471  Prod_16  SHP_3386   Cust_965     90.93      0.05   
15     Ord_956  Prod_16  SHP_1324   Cust_346    503.17      0.01   
16     Ord_975  Prod_16  SHP_1345   Cust_346    638.91      0.02   
19    Ord_4328  Prod_16  SHP_6033  Cust_1440    103.03      0.07   
...        ...      ...       ...        ...       ...       ...   
8382  Ord_5425  Prod_14  SHP_7580  Cust_1799  27720.98      0.07   
8384  Ord_1265  Prod_14  SHP_1749   Cust_466  24051.49      0.07   
8388   Ord_508  Prod_14   SHP_686   Cust_186  19109.61      0.10   
8390   Ord_546  Prod_14   SHP_858   Cust_198  27875.54      0.00   
8396  Ord_5368  Prod_14  SHP_7497  Cust_1795  17279.62      0.04   

      Order_Quantity    Profit  Shipping_Cost  Product_Base_Margin  \
11                42   -123.07           4.59                 0.82   
12                43    -72.50           2.56                 0.55   
15                46    -10.21           4.68                 0.59   
16                49     77.48           3.14                 0.60   
19                49    -82.63           2.56                 0.55   
...              ...       ...            ...                  ...   
8382              46  11984.40          24.49                 0.37   
8384              41   9791.04          24.49                 0.37   
8388              40   -379.29          24.49                 0.36   
8390              46   -635.69          24.49                 0.44   
8396              40   4176.25          24.49                 0.52   

     Product_Category           Product_Sub_Category  
11    OFFICE SUPPLIES  SCISSORS, RULERS AND TRIMMERS  
12    OFFICE SUPPLIES  SCISSORS, RULERS AND TRIMMERS  
15    OFFICE SUPPLIES  SCISSORS, RULERS AND TRIMMERS  
16    OFFICE SUPPLIES  SCISSORS, RULERS AND TRIMMERS  
19    OFFICE SUPPLIES  SCISSORS, RULERS AND TRIMMERS  
...               ...                            ...  
8382       TECHNOLOGY                COPIERS AND FAX  
8384       TECHNOLOGY                COPIERS AND FAX  
8388       TECHNOLOGY                COPIERS AND FAX  
8390       TECHNOLOGY                COPIERS AND FAX  
8396       TECHNOLOGY                COPIERS AND FAX  

[1875 rows x 12 columns]

In [95]:
sales0[(sales0.Order_Quantity>=40) & (sales0.Sales>=10000)]

Ord_id  Prod_id   Ship_id    Cust_id     Sales  Discount  \
2901  Ord_3707  Prod_17  SHP_5136  Cust_1307  28359.40      0.05   
2905  Ord_4857  Prod_17  SHP_6777   Cust_227  19100.45      0.00   
2916  Ord_1026  Prod_17  SHP_1417   Cust_363  15602.93      0.00   
2934  Ord_5181  Prod_17  SHP_7238  Cust_1750  23775.56      0.03   
2938   Ord_283  Prod_17   SHP_383    Cust_85  10051.52      0.05   
...        ...      ...       ...        ...       ...       ...   
8382  Ord_5425  Prod_14  SHP_7580  Cust_1799  27720.98      0.07   
8384  Ord_1265  Prod_14  SHP_1749   Cust_466  24051.49      0.07   
8388   Ord_508  Prod_14   SHP_686   Cust_186  19109.61      0.10   
8390   Ord_546  Prod_14   SHP_858   Cust_198  27875.54      0.00   
8396  Ord_5368  Prod_14  SHP_7497  Cust_1795  17279.62      0.04   

      Order_Quantity    Profit  Shipping_Cost  Product_Base_Margin  \
2901              49  14440.39          24.49                 0.37   
2905              40   6839.95          14.70                 0.56   
2916              48   4875.89          26.53                 0.56   
2934              44   7080.99          14.70                 0.59   
2938              48   4938.78          13.99                 0.37   
...              ...       ...            ...                  ...   
8382              46  11984.40          24.49                 0.37   
8384              41   9791.04          24.49                 0.37   
8388              40   -379.29          24.49                 0.36   
8390              46   -635.69          24.49                 0.44   
8396              40   4176.25          24.49                 0.52   

     Product_Category Product_Sub_Category  
2901       TECHNOLOGY      OFFICE MACHINES  
2905       TECHNOLOGY      OFFICE MACHINES  
2916       TECHNOLOGY      OFFICE MACHINES  
2934       TECHNOLOGY      OFFICE MACHINES  
2938       TECHNOLOGY      OFFICE MACHINES  
...               ...                  ...  
8382       TECHNOLOGY      COPIERS AND FAX  
8384       TECHNOLOGY      COPIERS AND FAX  
8388       TECHNOLOGY      COPIERS AND FAX  
8390       TECHNOLOGY      COPIERS AND FAX  
8396       TECHNOLOGY      COPIERS AND FAX  

[128 rows x 12 columns]

In [96]:
sales0[sales0['Product_Sub_Category'] == "OFFICE MACHINES"]

Ord_id  Prod_id   Ship_id    Cust_id     Sales  Discount  \
2885  Ord_5485  Prod_17  SHP_7664  Cust_1818   4233.15      0.08   
2886  Ord_5046  Prod_17  SHP_7042  Cust_1710    630.99      0.07   
2887  Ord_5215  Prod_17  SHP_7287  Cust_1749    140.59      0.01   
2888  Ord_5232  Prod_17  SHP_7306  Cust_1758  21366.51      0.00   
2889  Ord_5489  Prod_17  SHP_7671  Cust_1820    754.92      0.00   
...        ...      ...       ...        ...       ...       ...   
3217  Ord_3470  Prod_17  SHP_4805  Cust_1203   5615.40      0.07   
3218  Ord_4648  Prod_17  SHP_6479  Cust_1587    478.27      0.01   
3219  Ord_2622  Prod_17  SHP_3587  Cust_1016   2360.43      0.10   
3220  Ord_2077  Prod_17  SHP_2841   Cust_790    887.94      0.02   
3221  Ord_3592  Prod_17  SHP_4973  Cust_1266    636.50      0.01   

      Order_Quantity    Profit  Shipping_Cost  Product_Base_Margin  \
2885              35   1219.87          26.30                 0.38   
2886              49   -114.64           9.44                 0.39   
2887               7    -35.88           8.51                 0.40   
2888               3 -11984.40          24.49                 0.39   
2889               7   -129.57          19.99                 0.52   
...              ...       ...            ...                  ...   
3217              46   1807.16          26.30                 0.38   
3218              33     -4.85           7.51                 0.39   
3219              31     66.22          33.60                 0.37   
3220               7     49.45           7.11                 0.36   
3221              46    -71.98           9.44                 0.39   

     Product_Category Product_Sub_Category  
2885       TECHNOLOGY      OFFICE MACHINES  
2886       TECHNOLOGY      OFFICE MACHINES  
2887       TECHNOLOGY      OFFICE MACHINES  
2888       TECHNOLOGY      OFFICE MACHINES  
2889       TECHNOLOGY      OFFICE MACHINES  
...               ...                  ...  
3217       TECHNOLOGY      OFFICE MACHINES  
3218       TECHNOLOGY      OFFICE MACHINES  
3219       TECHNOLOGY      OFFICE MACHINES  
3220       TECHNOLOGY      OFFICE MACHINES  
3221       TECHNOLOGY      OFFICE MACHINES  

[337 rows x 12 columns]

#### Sorting dataframes

In [98]:
?sales0.sort_values

In [99]:
sales0.sort_values(by="Shipping_Cost")

Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
3294   Ord_428  Prod_12   SHP_572   Cust_148     28.810      0.02   
3334  Ord_2090  Prod_12  SHP_2859   Cust_796     53.910      0.05   
3413  Ord_3499  Prod_12  SHP_4846  Cust_1223     86.290      0.02   
3379  Ord_2400  Prod_12  SHP_3292   Cust_934     76.060      0.02   
3386  Ord_4122  Prod_12  SHP_5743  Cust_1408      6.130      0.08   
...        ...      ...       ...        ...        ...       ...   
5784  Ord_1581  Prod_15  SHP_2184   Cust_519   2573.920      0.07   
4076   Ord_417  Prod_11   SHP_561   Cust_156  20333.816      0.02   
4301  Ord_1741  Prod_11  SHP_2411   Cust_595  15168.820      0.02   
4189   Ord_839  Prod_11  SHP_1361   Cust_364  12689.870      0.04   
5736  Ord_1751  Prod_15  SHP_2426   Cust_597  14740.510      0.00   

      Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin  \
3294              10     7.15           0.49                 0.38   
3334              17    19.47           0.49                 0.37   
3413              17    34.98           0.49                 0.39   
3379              24    30.03           0.49                 0.37   
3386               2    -2.83           0.49                 0.38   
...              ...      ...            ...                  ...   
5784              17   117.23         143.71                 0.55   
4076              45 -1430.45         147.12                 0.80   
4301              26 -1096.78         147.12                 0.80   
4189              44  -169.23         154.12                 0.76   
5736              46  3407.73         164.73                 0.56   

     Product_Category Product_Sub_Category  
3294  OFFICE SUPPLIES               LABELS  
3334  OFFICE SUPPLIES               LABELS  
3413  OFFICE SUPPLIES               LABELS  
3379  OFFICE SUPPLIES               LABELS  
3386  OFFICE SUPPLIES               LABELS  
...               ...                  ...  
5784        FURNITURE   CHAIRS & CHAIRMATS  
4076        FURNITURE               TABLES  
4301        FURNITURE               TABLES  
4189        FURNITURE               TABLES  
5736        FURNITURE   CHAIRS & CHAIRMATS  

[8399 rows x 12 columns]

In [100]:
sales0.sort_values(by="Shipping_Cost", ascending=False)

Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
5736  Ord_1751  Prod_15  SHP_2426   Cust_597  14740.510      0.00   
4189   Ord_839  Prod_11  SHP_1361   Cust_364  12689.870      0.04   
4076   Ord_417  Prod_11   SHP_561   Cust_156  20333.816      0.02   
4301  Ord_1741  Prod_11  SHP_2411   Cust_595  15168.820      0.02   
5784  Ord_1581  Prod_15  SHP_2184   Cust_519   2573.920      0.07   
...        ...      ...       ...        ...        ...       ...   
3350  Ord_1558  Prod_12  SHP_2153   Cust_520   2905.300      0.00   
3272   Ord_284  Prod_12   SHP_384   Cust_105     97.130      0.05   
3276   Ord_189  Prod_12   SHP_255    Cust_97    345.200      0.01   
3404  Ord_3413  Prod_12  SHP_4731  Cust_1185    299.070      0.10   
3252   Ord_641  Prod_12   SHP_875   Cust_212    116.560      0.04   

      Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin  \
5736              46  3407.73         164.73                 0.56   
4189              44  -169.23         154.12                 0.76   
4076              45 -1430.45         147.12                 0.80   
4301              26 -1096.78         147.12                 0.80   
5784              17   117.23         143.71                 0.55   
...              ...      ...            ...                  ...   
3350              28  1704.00           0.49                 0.36   
3272               1   -37.06           0.49                 0.36   
3276              45   183.53           0.49                 0.38   
3404              26   137.47           0.49                 0.38   
3252              23    50.66           0.49                 0.39   

     Product_Category Product_Sub_Category  
5736        FURNITURE   CHAIRS & CHAIRMATS  
4189        FURNITURE               TABLES  
4076        FURNITURE               TABLES  
4301        FURNITURE               TABLES  
5784        FURNITURE   CHAIRS & CHAIRMATS  
...               ...                  ...  
3350  OFFICE SUPPLIES               LABELS  
3272  OFFICE SUPPLIES               LABELS  
3276  OFFICE SUPPLIES               LABELS  
3404  OFFICE SUPPLIES               LABELS  
3252  OFFICE SUPPLIES               LABELS  

[8399 rows x 12 columns]

In [102]:
sales0.sort_values(by=["Shipping_Cost", "Sales"], ascending=[True, False])

Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
3350  Ord_1558  Prod_12  SHP_2153   Cust_520   2905.300      0.00   
3375  Ord_4228  Prod_12  SHP_5901  Cust_1421   2455.540      0.03   
3296  Ord_2852  Prod_12  SHP_3925  Cust_1043    493.260      0.02   
3276   Ord_189  Prod_12   SHP_255    Cust_97    345.200      0.01   
3440  Ord_4252  Prod_12  SHP_5938  Cust_1446    312.630      0.01   
...        ...      ...       ...        ...        ...       ...   
5784  Ord_1581  Prod_15  SHP_2184   Cust_519   2573.920      0.07   
4076   Ord_417  Prod_11   SHP_561   Cust_156  20333.816      0.02   
4301  Ord_1741  Prod_11  SHP_2411   Cust_595  15168.820      0.02   
4189   Ord_839  Prod_11  SHP_1361   Cust_364  12689.870      0.04   
5736  Ord_1751  Prod_15  SHP_2426   Cust_597  14740.510      0.00   

      Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin  \
3350              28  1704.00           0.49                 0.36   
3375              25  1361.88           0.49                 0.36   
3296              39   263.40           0.49                 0.38   
3276              45   183.53           0.49                 0.38   
3440              40   167.30           0.49                 0.38   
...              ...      ...            ...                  ...   
5784              17   117.23         143.71                 0.55   
4076              45 -1430.45         147.12                 0.80   
4301              26 -1096.78         147.12                 0.80   
4189              44  -169.23         154.12                 0.76   
5736              46  3407.73         164.73                 0.56   

     Product_Category Product_Sub_Category  
3350  OFFICE SUPPLIES               LABELS  
3375  OFFICE SUPPLIES               LABELS  
3296  OFFICE SUPPLIES               LABELS  
3276  OFFICE SUPPLIES               LABELS  
3440  OFFICE SUPPLIES               LABELS  
...               ...                  ...  
5784        FURNITURE   CHAIRS & CHAIRMATS  
4076        FURNITURE               TABLES  
4301        FURNITURE               TABLES  
4189        FURNITURE               TABLES  
5736        FURNITURE   CHAIRS & CHAIRMATS  

[8399 rows x 12 columns]

#### Editing values in a dataframe

In [110]:
sales0.loc[sales0.Product_Sub_Category=="CHAIRS & CHAIRMATS", "Product_Sub_Category"] = "CHAIRS & MATS"

In [112]:
sales0[sales0.Product_Sub_Category=="CHAIRS & MATS"].shape

(386, 12)

#### Combining data - merging data

Load the customer data

In [113]:
customer0 = pd.read_csv("customer_data.csv")
customer0.head()

Customer_Name Province   Region Customer_Segment Cust_id
0  MUHAMMED MACINTYRE  NUNAVUT  NUNAVUT   SMALL BUSINESS  Cust_1
1        BARRY FRENCH  NUNAVUT  NUNAVUT         CONSUMER  Cust_2
2       CLAY ROZENDAL  NUNAVUT  NUNAVUT        CORPORATE  Cust_3
3      CARLOS SOLTERO  NUNAVUT  NUNAVUT         CONSUMER  Cust_4
4        CARL JACKSON  NUNAVUT  NUNAVUT        CORPORATE  Cust_5

In [114]:
sales0.head()

Ord_id  Prod_id   Ship_id    Cust_id   Sales  Discount  Order_Quantity  \
0  Ord_5446  Prod_16  SHP_7609  Cust_1818  136.81      0.01              23   
1  Ord_2978  Prod_16  SHP_4112  Cust_1088  305.05      0.04              27   
2  Ord_5484  Prod_16  SHP_7663  Cust_1820  322.82      0.05              35   
3  Ord_3730  Prod_16  SHP_5175  Cust_1314  459.08      0.04              34   
4  Ord_4143  Prod_16  SHP_5771  Cust_1417  207.21      0.06              24   

   Profit  Shipping_Cost  Product_Base_Margin Product_Category  \
0  -30.51           3.60                 0.56  OFFICE SUPPLIES   
1   23.12           3.37                 0.57  OFFICE SUPPLIES   
2  -17.58           3.98                 0.56  OFFICE SUPPLIES   
3   61.57           3.14                 0.60  OFFICE SUPPLIES   
4  -78.64           6.14                 0.59  OFFICE SUPPLIES   

            Product_Sub_Category  
0  SCISSORS, RULERS AND TRIMMERS  
1  SCISSORS, RULERS AND TRIMMERS  
2  SCISSORS, RULERS AND TRIMMERS  
3  SCISSORS, RULERS AND TRIMMERS  
4  SCISSORS, RULERS AND TRIMMERS

In [115]:
?pd.merge

In [117]:
comb0 = pd.merge(sales0, customer0, left_on="Cust_id", right_on="Cust_id", how="inner")

In [118]:
comb0.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8399 entries, 0 to 8398
Data columns (total 16 columns):
Ord_id                  8399 non-null object
Prod_id                 8399 non-null object
Ship_id                 8399 non-null object
Cust_id                 8399 non-null object
Sales                   8399 non-null float64
Discount                8399 non-null float64
Order_Quantity          8399 non-null int64
Profit                  8399 non-null float64
Shipping_Cost           8399 non-null float64
Product_Base_Margin     8336 non-null float64
Product_Category        8399 non-null object
Product_Sub_Category    8399 non-null object
Customer_Name           8399 non-null object
Province                8399 non-null object
Region                  8399 non-null object
Customer_Segment        8399 non-null object
dtypes: float64(5), int64(1), object(10)
memory usage: 1.1+ MB


In [120]:
comb0.head()

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity  \
0  Ord_5446  Prod_16  SHP_7609  Cust_1818   136.81      0.01              23   
1  Ord_5406  Prod_13  SHP_7549  Cust_1818    42.27      0.01              13   
2  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00              26   
3  Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.89      0.09              43   
4  Ord_5446   Prod_6  SHP_7608  Cust_1818   164.02      0.03              23   

    Profit  Shipping_Cost  Product_Base_Margin Product_Category  \
0   -30.51           3.60                 0.56  OFFICE SUPPLIES   
1     4.56           0.93                 0.54  OFFICE SUPPLIES   
2  1148.90           2.50                 0.59       TECHNOLOGY   
3   729.34          14.30                 0.37  OFFICE SUPPLIES   
4   -47.64           6.15                 0.37  OFFICE SUPPLIES   

            Product_Sub_Category  Customer_Name Province Region  \
0  SCISSORS, RULERS AND TRIMMERS  AARON BERGMAN  ALBERTA   WEST   
1            PENS & ART SUPPLIES  AARON BERGMAN  ALBERTA   WEST   
2   TELEPHONES AND COMMUNICATION  AARON BERGMAN  ALBERTA   WEST   
3                          PAPER  AARON BERGMAN  ALBERTA   WEST   
4                          PAPER  AARON BERGMAN  ALBERTA   WEST   

  Customer_Segment  
0        CORPORATE  
1        CORPORATE  
2        CORPORATE  
3        CORPORATE  
4        CORPORATE

#### Dropping or deleting values from a dataframe

In [124]:
sales0.drop(["Ship_id","Ord_id"],axis=1)

Prod_id    Cust_id     Sales  Discount  Order_Quantity   Profit  \
0     Prod_16  Cust_1818    136.81      0.01              23   -30.51   
1     Prod_16  Cust_1088    305.05      0.04              27    23.12   
2     Prod_16  Cust_1820    322.82      0.05              35   -17.58   
3     Prod_16  Cust_1314    459.08      0.04              34    61.57   
4     Prod_16  Cust_1417    207.21      0.06              24   -78.64   
...       ...        ...       ...       ...             ...      ...   
8394  Prod_14  Cust_1803   5964.19      0.10              33   988.20   
8395  Prod_14   Cust_247  27663.92      0.05               8  -391.92   
8396  Prod_14  Cust_1795  17279.62      0.04              40  4176.25   
8397  Prod_14   Cust_595  14647.26      0.07              25  5485.15   
8398  Prod_14  Cust_1266   1759.65      0.06               3 -2213.75   

      Shipping_Cost  Product_Base_Margin Product_Category  \
0              3.60                 0.56  OFFICE SUPPLIES   
1              3.37                 0.57  OFFICE SUPPLIES   
2              3.98                 0.56  OFFICE SUPPLIES   
3              3.14                 0.60  OFFICE SUPPLIES   
4              6.14                 0.59  OFFICE SUPPLIES   
...             ...                  ...              ...   
8394          24.49                 0.46       TECHNOLOGY   
8395          24.49                 0.37       TECHNOLOGY   
8396          24.49                 0.52       TECHNOLOGY   
8397          24.49                 0.37       TECHNOLOGY   
8398          24.49                 0.50       TECHNOLOGY   

               Product_Sub_Category  
0     SCISSORS, RULERS AND TRIMMERS  
1     SCISSORS, RULERS AND TRIMMERS  
2     SCISSORS, RULERS AND TRIMMERS  
3     SCISSORS, RULERS AND TRIMMERS  
4     SCISSORS, RULERS AND TRIMMERS  
...                             ...  
8394                COPIERS AND FAX  
8395                COPIERS AND FAX  
8396                COPIERS AND FAX  
8397                COPIERS AND FAX  
8398                COPIERS AND FAX  

[8399 rows x 10 columns]

In [126]:
sales1 = sales0[~(sales0.Product_Category == "TECHNOLOGY")]

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  \
0     Ord_5446  Prod_16  SHP_7609  Cust_1818   136.81      0.01   
1     Ord_2978  Prod_16  SHP_4112  Cust_1088   305.05      0.04   
2     Ord_5484  Prod_16  SHP_7663  Cust_1820   322.82      0.05   
3     Ord_3730  Prod_16  SHP_5175  Cust_1314   459.08      0.04   
4     Ord_4143  Prod_16  SHP_5771  Cust_1417   207.21      0.06   
...        ...      ...       ...        ...      ...       ...   
7549  Ord_2172   Prod_1  SHP_2960   Cust_787  6648.58      0.08   
7550  Ord_2780   Prod_1  SHP_3819  Cust_1016  2014.13      0.10   
7551  Ord_3543   Prod_1  SHP_4905  Cust_1266  1184.11      0.07   
7552  Ord_2722   Prod_1  SHP_3731  Cust_1006  3508.33      0.04   
7553  Ord_4424   Prod_1  SHP_6165  Cust_1519   994.04      0.03   

      Order_Quantity  Profit  Shipping_Cost  Product_Base_Margin  \
0                 23  -30.51           3.60                 0.56   
1                 27   23.12           3.37                 0.57   
2                 35  -17.58           3.98                 0.56   
3                 34   61.57           3.14                 0.60   
4                 24  -78.64           6.14                 0.59   
...              ...     ...            ...                  ...   
7549              19 -555.98          99.00                 0.65   
7550              24 -794.94          35.00                 0.83   
7551               6 -145.07          19.99                 0.71   
7552              21 -546.98          35.00                 0.85   
7553              10 -335.06          35.00                  NaN   

     Product_Category           Product_Sub_Category  
0     OFFICE SUPPLIES  SCISSORS, RULERS AND TRIMMERS  
1     OFFICE SUPPLIES  SCISSORS, RULERS AND TRIMMERS  
2     OFFICE SUPPLIES  SCISSORS, RULERS AND TRIMMERS  
3     OFFICE SUPPLIES  SCISSORS, RULERS AND TRIMMERS  
4     OFFICE SUPPLIES  SCISSORS, RULERS AND TRIMMERS  
...               ...                            ...  
7549  OFFICE SUPPLIES         STORAGE & ORGANIZATION  
7550  OFFICE SUPPLIES         STORAGE & ORGANIZATION  
7551  OFFICE SUPPLIES         STORAGE & ORGANIZATION  
7552  OFFICE SUPPLIES         STORAGE & ORGANIZATION  
7553  OFFICE SUPPLIES         STORAGE & ORGANIZATION  

[6334 rows x 12 columns]

#### Summaries and groupby

In [127]:
sales0.Sales.sum()

14915600.824

In [129]:
sales0[["Sales", "Order_Quantity", "Shipping_Cost", "Profit"]].sum()

Sales             1.491560e+07
Order_Quantity    2.147770e+05
Shipping_Cost     1.078310e+05
Profit            1.521768e+06
dtype: float64

In [130]:
sales0[["Sales", "Order_Quantity", "Shipping_Cost", "Profit"]].mean()

Sales             1775.878179
Order_Quantity      25.571735
Shipping_Cost       12.838557
Profit             181.184424
dtype: float64

In [131]:
comb0.head()

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity  \
0  Ord_5446  Prod_16  SHP_7609  Cust_1818   136.81      0.01              23   
1  Ord_5406  Prod_13  SHP_7549  Cust_1818    42.27      0.01              13   
2  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00              26   
3  Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.89      0.09              43   
4  Ord_5446   Prod_6  SHP_7608  Cust_1818   164.02      0.03              23   

    Profit  Shipping_Cost  Product_Base_Margin Product_Category  \
0   -30.51           3.60                 0.56  OFFICE SUPPLIES   
1     4.56           0.93                 0.54  OFFICE SUPPLIES   
2  1148.90           2.50                 0.59       TECHNOLOGY   
3   729.34          14.30                 0.37  OFFICE SUPPLIES   
4   -47.64           6.15                 0.37  OFFICE SUPPLIES   

            Product_Sub_Category  Customer_Name Province Region  \
0  SCISSORS, RULERS AND TRIMMERS  AARON BERGMAN  ALBERTA   WEST   
1            PENS & ART SUPPLIES  AARON BERGMAN  ALBERTA   WEST   
2   TELEPHONES AND COMMUNICATION  AARON BERGMAN  ALBERTA   WEST   
3                          PAPER  AARON BERGMAN  ALBERTA   WEST   
4                          PAPER  AARON BERGMAN  ALBERTA   WEST   

  Customer_Segment  
0        CORPORATE  
1        CORPORATE  
2        CORPORATE  
3        CORPORATE  
4        CORPORATE

In [132]:
comb0.Customer_Segment.value_counts()

CORPORATE         3076
HOME OFFICE       2032
CONSUMER          1649
SMALL BUSINESS    1642
Name: Customer_Segment, dtype: int64

In [133]:
comb0.Customer_Segment.value_counts(normalize=True)

CORPORATE         0.366234
HOME OFFICE       0.241934
CONSUMER          0.196333
SMALL BUSINESS    0.195499
Name: Customer_Segment, dtype: float64

Group-by

In [135]:
comb0.groupby(["Customer_Segment"])[['Sales']].sum()

Sales
Customer_Segment              
CONSUMER          3.063611e+06
CORPORATE         5.498905e+06
HOME OFFICE       3.564764e+06
SMALL BUSINESS    2.788321e+06

In [136]:
comb0.groupby(["Customer_Segment"])[['Sales','Profit']].mean()

Sales      Profit
Customer_Segment                         
CONSUMER          1857.859965  174.627010
CORPORATE         1787.680389  194.975943
HOME OFFICE       1754.312931  156.670290
SMALL BUSINESS    1698.124841  192.270408

In [137]:
comb0.groupby(["Customer_Segment","Product_Category"])[['Sales','Profit']].mean()

Sales      Profit
Customer_Segment Product_Category                         
CONSUMER         FURNITURE         3153.092777  119.352682
                 OFFICE SUPPLIES    799.285815  102.349468
                 TECHNOLOGY        2918.830136  367.838944
CORPORATE        FURNITURE         2942.876104   34.767899
                 OFFICE SUPPLIES    798.402161  120.855583
                 TECHNOLOGY        3007.534303  491.088519
HOME OFFICE      FURNITURE         3165.876645   59.062069
                 OFFICE SUPPLIES    838.475467  105.804061
                 TECHNOLOGY        2742.959557  360.143825
SMALL BUSINESS   FURNITURE         2757.176869   87.821070
                 OFFICE SUPPLIES    826.097641  114.463163
                 TECHNOLOGY        2852.441325  459.960532

#### Pivot tables

In [141]:
pd.pivot_table(data=comb0,
               index="Product_Sub_Category",
               columns="Customer_Segment",
               values="Sales", 
               aggfunc=np.mean)

Customer_Segment                    CONSUMER     CORPORATE   HOME OFFICE  \
Product_Sub_Category                                                       
APPLIANCES                       1538.869315   1656.230950   1802.528558   
BINDERS AND BINDER ACCESSORIES    970.386047   1177.114257   1116.078690   
BOOKCASES                        4390.945952   4653.822063   4534.396279   
CHAIRS & MATS                    4742.216203   4547.559195   4638.791264   
COMPUTER PERIPHERALS              802.037987   1158.703007   1114.127253   
COPIERS AND FAX                 13706.856471  11747.600645  13070.738947   
ENVELOPES                         678.087619    651.264045    684.869038   
LABELS                            101.181475    147.105825    109.703380   
OFFICE FURNISHINGS                814.267707    778.833459   1177.451263   
OFFICE MACHINES                  7278.692027   6998.280394   5458.378400   
PAPER                             360.910983    361.472079    359.042548   
PENS & ART SUPPLIES               305.974298    256.793966    222.555267   
RUBBER BANDS                      102.629655     78.020492     87.376444   
SCISSORS, RULERS AND TRIMMERS    1050.176786    412.684821    606.243077   
STORAGE & ORGANIZATION           2129.803333   1763.836304   2078.244069   
TABLES                           5523.904675   5152.279798   5384.608116   
TELEPHONES AND COMMUNICATION     1924.132696   2194.496698   2238.390083   

Customer_Segment                SMALL BUSINESS  
Product_Sub_Category                            
APPLIANCES                         1804.176538  
BINDERS AND BINDER ACCESSORIES     1150.403392  
BOOKCASES                          3660.060488  
CHAIRS & MATS                      4310.426901  
COMPUTER PERIPHERALS               1025.951370  
COPIERS AND FAX                   14241.254000  
ENVELOPES                           825.879841  
LABELS                              186.200755  
OFFICE FURNISHINGS                  799.454161  
OFFICE MACHINES                    5441.212131  
PAPER                               379.393083  
PENS & ART SUPPLIES                 286.726960  
RUBBER BANDS                         75.890455  
SCISSORS, RULERS AND TRIMMERS       230.358571  
STORAGE & ORGANIZATION             1970.196250  
TABLES                             4945.081455  
TELEPHONES AND COMMUNICATION       2143.966687

In [143]:
res = pd.pivot_table(data=comb0,
               index=["Product_Category", "Product_Sub_Category"],
               columns="Customer_Segment",
               values="Sales", 
               aggfunc=np.mean)
res

Customer_Segment                                     CONSUMER     CORPORATE  \
Product_Category Product_Sub_Category                                         
FURNITURE        BOOKCASES                        4390.945952   4653.822063   
                 CHAIRS & MATS                    4742.216203   4547.559195   
                 OFFICE FURNISHINGS                814.267707    778.833459   
                 TABLES                           5523.904675   5152.279798   
OFFICE SUPPLIES  APPLIANCES                       1538.869315   1656.230950   
                 BINDERS AND BINDER ACCESSORIES    970.386047   1177.114257   
                 ENVELOPES                         678.087619    651.264045   
                 LABELS                            101.181475    147.105825   
                 PAPER                             360.910983    361.472079   
                 PENS & ART SUPPLIES               305.974298    256.793966   
                 RUBBER BANDS                      102.629655     78.020492   
                 SCISSORS, RULERS AND TRIMMERS    1050.176786    412.684821   
                 STORAGE & ORGANIZATION           2129.803333   1763.836304   
TECHNOLOGY       COMPUTER PERIPHERALS              802.037987   1158.703007   
                 COPIERS AND FAX                 13706.856471  11747.600645   
                 OFFICE MACHINES                  7278.692027   6998.280394   
                 TELEPHONES AND COMMUNICATION     1924.132696   2194.496698   

Customer_Segment                                  HOME OFFICE  SMALL BUSINESS  
Product_Category Product_Sub_Category                                          
FURNITURE        BOOKCASES                        4534.396279     3660.060488  
                 CHAIRS & MATS                    4638.791264     4310.426901  
                 OFFICE FURNISHINGS               1177.451263      799.454161  
                 TABLES                           5384.608116     4945.081455  
OFFICE SUPPLIES  APPLIANCES                       1802.528558     1804.176538  
                 BINDERS AND BINDER ACCESSORIES   1116.078690     1150.403392  
                 ENVELOPES                         684.869038      825.879841  
                 LABELS                            109.703380      186.200755  
                 PAPER                             359.042548      379.393083  
                 PENS & ART SUPPLIES               222.555267      286.726960  
                 RUBBER BANDS                       87.376444       75.890455  
                 SCISSORS, RULERS AND TRIMMERS     606.243077      230.358571  
                 STORAGE & ORGANIZATION           2078.244069     1970.196250  
TECHNOLOGY       COMPUTER PERIPHERALS             1114.127253     1025.951370  
                 COPIERS AND FAX                 13070.738947    14241.254000  
                 OFFICE MACHINES                  5458.378400     5441.212131  
                 TELEPHONES AND COMMUNICATION     2238.390083     2143.966687

In [144]:
type(res)

pandas.core.frame.DataFrame

In [145]:
res = pd.pivot_table(data=comb0,
               index=["Product_Category"],
               columns="Customer_Segment",
               values=["Sales","Profit"], 
               aggfunc=np.mean)
res

Profit                                         \
Customer_Segment    CONSUMER   CORPORATE HOME OFFICE SMALL BUSINESS   
Product_Category                                                      
FURNITURE         119.352682   34.767899   59.062069      87.821070   
OFFICE SUPPLIES   102.349468  120.855583  105.804061     114.463163   
TECHNOLOGY        367.838944  491.088519  360.143825     459.960532   

                        Sales                                           
Customer_Segment     CONSUMER    CORPORATE  HOME OFFICE SMALL BUSINESS  
Product_Category                                                        
FURNITURE         3153.092777  2942.876104  3165.876645    2757.176869  
OFFICE SUPPLIES    799.285815   798.402161   838.475467     826.097641  
TECHNOLOGY        2918.830136  3007.534303  2742.959557    2852.441325

In [146]:
res = pd.pivot_table(data=comb0,
               index=["Product_Category"],
               columns="Customer_Segment",
               values=["Sales","Profit"], 
               aggfunc={"Sales":sum, "Profit":np.mean})
res

Profit                                         \
Customer_Segment    CONSUMER   CORPORATE HOME OFFICE SMALL BUSINESS   
Product_Category                                                      
FURNITURE         119.352682   34.767899   59.062069      87.821070   
OFFICE SUPPLIES   102.349468  120.855583  105.804061     114.463163   
TECHNOLOGY        367.838944  491.088519  360.143825     459.960532   

                        Sales                                            
Customer_Segment     CONSUMER     CORPORATE  HOME OFFICE SMALL BUSINESS  
Product_Category                                                         
FURNITURE         1128807.214  1.862841e+06  1285345.918   9.015968e+05  
OFFICE SUPPLIES    691382.230  1.341316e+06   960054.410   7.600098e+05  
TECHNOLOGY        1243421.638  2.294749e+06  1319363.547   1.126714e+06

#### Saving your dataframes

In [147]:
comb0.to_csv("combined_store_data.csv", index=False)

In [149]:
type(res)

pandas.core.frame.DataFrame

In [150]:
res

Profit                                         \
Customer_Segment    CONSUMER   CORPORATE HOME OFFICE SMALL BUSINESS   
Product_Category                                                      
FURNITURE         119.352682   34.767899   59.062069      87.821070   
OFFICE SUPPLIES   102.349468  120.855583  105.804061     114.463163   
TECHNOLOGY        367.838944  491.088519  360.143825     459.960532   

                        Sales                                            
Customer_Segment     CONSUMER     CORPORATE  HOME OFFICE SMALL BUSINESS  
Product_Category                                                         
FURNITURE         1128807.214  1.862841e+06  1285345.918   9.015968e+05  
OFFICE SUPPLIES    691382.230  1.341316e+06   960054.410   7.600098e+05  
TECHNOLOGY        1243421.638  2.294749e+06  1319363.547   1.126714e+06

In [151]:
res.to_csv("cat_segment_analysis.csv")

In [ ]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
P = pd.DataFrame(min_max_scaler.fit_transform(Latest), columns = Latest.columns)
P.churn.mean()

In [ ]:
min_max_scaler = preprocessing.MinMaxScaler()
S = pd.DataFrame(min_max_scaler.fit_transform(new_cluster), columns = new_cluster.columns)
S.mean()